FROM amazoncorretto:21 AS builder
WORKDIR /app
COPY gradle gradle
COPY gradlew gradlew
COPY build.gradle.kts build.gradle.kts
COPY settings.gradle.kts settings.gradle.kts
COPY spotless.xml spotless.xml
RUN ./gradlew check --dry-run
COPY src src
RUN ./gradlew clean build

FROM amazoncorretto:21
ARG SERVER_PORT
ARG PG_HOST
ARG PG_PORT
ARG PG_DATABASE
ARG PG_USERNAME
ARG PG_PASSWORD
ARG MONGO_CONNECTION_URI
ARG MONGO_DATABASE
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG OTP_SECRET_TOKEN
ARG AUTH_TOKEN_PUBLIC_KEY
ARG AUTH_TOKEN_PRIVATE_KEY
WORKDIR /app
COPY --from=builder /app/build/libs/users-service-1.0.0-fat.jar app.jar
ENV SERVER_PORT $SERVER_PORT
ENV PG_HOST $PG_HOST
ENV PG_PORT $PG_PORT
ENV PG_DATABASE $PG_DATABASE
ENV PG_USERNAME $PG_USERNAME
ENV PG_PASSWORD $PG_PASSWORD
ENV MONGO_CONNECTION_URI $MONGO_CONNECTION_URI
ENV MONGO_DATABASE $MONGO_DATABASE
ENV MAIL_USERNAME $MAIL_USERNAME
ENV MAIL_PASSWORD $MAIL_PASSWORD
ENV OTP_SECRET_TOKEN $OTP_SECRET_TOKEN
ENV AUTH_TOKEN_PUBLIC_KEY $AUTH_TOKEN_PUBLIC_KEY
ENV AUTH_TOKEN_PRIVATE_KEY $AUTH_TOKEN_PRIVATE_KEY
CMD java -jar app.jar
